kind: Service
apiVersion: v1
metadata:
  name: configmap-demo
spec:
  selector:
    app: configmap-demo
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30083
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-demo
  namespace: default
spec:
  selector:
      matchLabels:
        app: configmap-demo

  replicas: 1
  template:
    metadata:
      labels:
        app: configmap-demo
    spec:
      containers:
        - name: configmap-demo
          image: configmap-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: env.namespace
              value: test
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: configmap-demo
